name: CI

on: [push]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Android App Bundle
      uses: steebchen/flutter@v1.0.0
      run: |
        flutter build appbundle --release
